services:

  proxy:
    build:
      context: ../../
      dockerfile: ./examples/envoy-plugin/envoy/Dockerfile
      args:
        ENVOY_VARIANT: contrib-v1.26.2
        ENVOY_CONFIG: examples/envoy-plugin/envoy.yaml
    depends_on:
      hello_service:
        condition: service_healthy
    ports:
    - "${PORT_PROXY:-10000}:10000"

  hello_service:
    build:
      context: ../../
      dockerfile: ./examples/envoy-plugin/hello/Dockerfile
    ports:
    - "${PORT:-8080}:8080"

